---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: always
  image: pelotech/drone-helm3
  settings:
    helm_command: lint
    chart: ./

- name: discord
  pull: always
  image: appleboy/drone-discord:1.0.0
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    status:
    - changed
    - failure

---
kind: pipeline
name: release-version

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - tag

steps:
  - name: generate-chart
    pull: default
    image: alpine:3.12
    commands:
      - wget -q https://get.helm.sh/helm-v3.3.1-linux-arm64.tar.gz -O - | tar -xzO linux-arm64/helm > /usr/local/bin/helm
      - chmod +x /usr/local/bin/helm
      - helm dependency update
      - helm package ./
      - mkdir gitea
      - mv gitea*.tgz gitea/
      - wget -O gitea/index.yaml https://dl.gitea.io/charts/index.yaml
      - helm repo index gitea/ --url https://dl.gitea.io/charts --merge gitea/index.yaml

  - name: upload-chart
    pull: default
    image: plugins/s3:latest
    settings:
      bucket: releases
      endpoint: https://storage.gitea.io
      path_style: true
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: gitea/*
      target: /charts
      strip_prefix: gitea/